version: "3.9"

services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis